package cobracurl

import (
	"github.com/spf13/pflag"
)

func RegisterFlags(flags *pflag.FlagSet) {
	flags.String("abstract-unix-socket", "", "Connect via abstract Unix domain socket")
	flags.String("alt-svc", "", "Enable alt-svc with this cache file")
	flags.Bool("anyauth", false, "Pick any auth method")
	flags.BoolP("append", "a", false, "Append to target file(s) instead of overwriting")
	flags.String("aws-sigv4", "", "Use AWS V4 signature authentication")
	flags.Bool("basic", false, "Use HTTP Basic Auth (use with -u)")
	flags.String("cacert", "", "CA certificate to verify peer against")
	flags.String("capath", "", "CA directory to verify peer against")
	flags.Bool("ca-native", false, "Use native CA store")
	flags.StringP("cert", "E", "", "Client certificate file")
	flags.Bool("cert-status", false, "Verify the status of the server certificate")
	flags.String("cert-type", "", "Certificate file type (DER/PEM/ENG/P12)")
	flags.String("ciphers", "", "SSL ciphers to use")
	flags.Bool("compressed", false, "Request compressed response")
	flags.StringP("config", "K", "", "Read config from a file")
	flags.Float64("connect-timeout", 0, "Maximum time allowed for connection")
	flags.String("connect-to", "", "Connect to host")
	flags.Int64P("continue-at", "C", 0, "Resumed transfer offset")
	flags.StringP("cookie", "b", "", "Send cookies from string/file")
	flags.StringP("cookie-jar", "c", "", "Write cookies to <file> after operation")
	flags.Bool("create-dirs", false, "Create necessary local directory hierarchy")
	flags.String("create-file-mode", "", "File mode for created files")
	flags.Bool("crlf", false, "Convert LF to CRLF in upload")
	flags.String("crlfile", "", "Use a CRL list")
	flags.String("curves", "", "SSL/TLS key exchange algorithm(s) to request")
	flags.StringP("data", "d", "", "HTTP POST data")
	flags.String("data-ascii", "", "HTTP POST ASCII data")
	flags.String("data-binary", "", "HTTP POST binary data")
	flags.String("data-raw", "", "HTTP POST data, @ is not special")
	flags.String("data-urlencode", "", "HTTP POST data URL encoded")
	flags.String("delegation", "", "GSS-API delegation permission")
	flags.Bool("digest", false, "Use HTTP Digest Auth (use with -u)")
	flags.BoolP("disable", "q", false, "Disable .curlrc")
	flags.Bool("disable-eprt", false, "Inhibit using EPRT or LPRT")
	flags.Bool("disable-epsv", false, "Inhibit using EPSV")
	flags.Bool("doh-cert-status", false, "Verify DoH server certificate status")
	flags.Bool("doh-insecure", false, "Allow insecure DoH server connections")
	flags.String("doh-url", "", "Resolve host names over DOH")
	flags.StringP("dump-header", "D", "", "Write the received headers to <file>")
	flags.String("ech", "", "Configure ECH")
	flags.String("egd-file", "", "EGD socket path for entropy")
	flags.String("engine", "", "OpenSSL crypto engine to use")
	flags.String("etag-compare", "", "Pass an ETag to compare on conditional requests")
	flags.String("etag-save", "", "Parse and save an ETag in the HTTP response")
	flags.Int("expect100-timeout", 0, "How long to wait for 100-continue")
	flags.BoolP("fail", "f", false, "Fail fast with no output on HTTP errors")
	flags.Bool("fail-early", false, "Fail on first transfer error, do not continue")
	flags.Bool("fail-with-body", false, "Fail on HTTP errors but save the body")
	flags.Bool("false-start", false, "Enable TLS False Start")
	flags.StringP("form", "F", "", "Specify multipart MIME data")
	flags.Bool("form-escape", false, "Escape multipart form field/file names")
	flags.String("form-string", "", "Specify multipart MIME data")
	flags.String("ftp-account", "", "Account data string")
	flags.String("ftp-alternative-to-user", "", "String to replace USER [name]")
	flags.Bool("ftp-create-dirs", false, "Create the remote dirs if not present")
	flags.String("ftp-method", "", "Specify CWD method")
	flags.Bool("ftp-pasv", false, "Use PASV/EPSV instead of PORT")
	flags.StringP("ftp-port", "P", "", "Use PORT instead of PASV")
	flags.Bool("ftp-pret", false, "Send PRET before PASV")
	flags.Bool("ftp-skip-pasv-ip", false, "Skip the IP address for PASV")
	flags.Bool("ftp-ssl-ccc", false, "Send CCC after authenticating")
	flags.String("ftp-ssl-ccc-mode", "", "Set CCC mode")
	flags.Bool("ftp-ssl-control", false, "Require SSL/TLS for FTP login, clear for transfer")
	flags.BoolP("get", "G", false, "Put the post data in the URL and use GET")
	flags.BoolP("globoff", "g", false, "Disable URL sequences and ranges")
	flags.Int("happy-eyeballs-timeout-ms", 0, "How long to wait for IPv6 before using IPv4")
	flags.Bool("haproxy-protocol", false, "Send HAProxy PROXY protocol v1 header")
	flags.BoolP("head", "I", false, "Show document info only")
	flags.StringP("header", "H", "", "Pass custom header(s) to server")
	flags.String("hostpubmd5", "", "Acceptable MD5 hash of the host public key")
	flags.String("hsts", "", "Enable HSTS with this cache file")
	flags.Bool("http0.9", false, "Allow HTTP 0.9 responses")
	flags.BoolP("http1.0", "0", false, "Use HTTP 1.0")
	flags.Bool("http1.1", false, "Use HTTP 1.1")
	flags.Bool("http2", false, "Use HTTP 2")
	flags.Bool("http2-prior-knowledge", false, "Use HTTP 2 without HTTP/1.1 Upgrade")
	flags.Bool("http3", false, "Use HTTP v3")
	flags.Bool("http3-only", false, "Use HTTP v3 only")
	flags.Bool("ignore-content-length", false, "Ignore the size of the remote resource")
	flags.String("interface", "", "Use network INTERFACE (or address)")
	flags.BoolP("ipv4", "4", false, "Resolve to IPv4 addresses")
	flags.BoolP("ipv6", "6", false, "Resolve to IPv6 addresses")
	flags.String("json", "", "HTTP POST JSON")
	flags.BoolP("junk-session-cookies", "j", false, "Ignore session cookies read from file")
	flags.Int("keepalive-time", 0, "Wait seconds before sending keepalive probes")
	flags.String("key", "", "Private key file name")
	flags.String("key-type", "", "Private key file type (DER/PEM/ENG)")
	flags.String("krb", "", "Enable Kerberos with security <level>")
	flags.String("limit-rate", "", "Limit transfer speed to <speed>")
	flags.BoolP("list-only", "l", false, "List only mode")
	flags.String("local-port", "", "Force use of Range of local port numbers")
	flags.BoolP("location", "L", false, "Follow redirects")
	flags.Bool("location-trusted", false, "Follow redirects, trust all hosts")
	flags.String("login-options", "", "Server login options")
	flags.String("mail-auth", "", "Originator address of the original email")
	flags.String("mail-from", "", "Mail from this address")
	flags.String("mail-rcpt", "", "Mail to this address")
	flags.Int64("max-filesize", 0, "Maximum file size to download")
	flags.Int("max-redirs", 0, "Maximum number of redirects allowed")
	flags.Float64P("max-time", "m", 0, "Maximum time allowed for the transfer")
	flags.Bool("metalink", false, "Process given URLs as metalink XML file")
	flags.Bool("negotiate", false, "Use SPNEGO (Negotiate) authentication")
	flags.Bool("netrc", false, "Must read .netrc for user name and password")
	flags.String("netrc-file", "", "Specify FILE for netrc")
	flags.Bool("netrc-optional", false, "Use either .netrc or URL")
	flags.Bool("next", false, "Allows several URLs in a single command line")
	flags.Bool("no-alpn", false, "Disable the ALPN TLS extension")
	flags.BoolP("no-buffer", "N", false, "Disable buffering of the output stream")
	flags.Bool("no-clobber", false, "Do not overwrite files")
	flags.Bool("no-keepalive", false, "Disable TCP keepalive on the connection")
	flags.Bool("no-npn", false, "Disable the NPN TLS extension")
	flags.Bool("no-progress-meter", false, "Do not show the progress meter")
	flags.Bool("no-sessionid", false, "Disable SSL session-ID reusing")
	flags.String("noproxy", "", "List of hosts which do not use proxy")
	flags.Bool("ntlm", false, "Use NTLM authentication")
	flags.Bool("ntlm-wb", false, "Use NTLM authentication with winbind")
	flags.String("oauth2-bearer", "", "OAuth 2 Bearer Token")
	flags.StringP("output", "o", "", "Write to file instead of stdout")
	flags.String("output-dir", "", "Directory to save downloads")
	flags.String("pass", "", "Pass phrase for the private key")
	flags.BoolP("parallel", "Z", false, "Perform transfers in parallel")
	flags.Bool("parallel-immediate", false, "Do not wait for multiplexing")
	flags.Int("parallel-max", 0, "Maximum concurrent parallel transfers")
	flags.Bool("path-as-is", false, "Do not squash .. sequences in URL path")
	flags.String("pinnedpubkey", "", "FILE/HASHES public key to verify peer against")
	flags.Bool("post301", false, "Do not switch to GET after following a 301")
	flags.Bool("post302", false, "Do not switch to GET after following a 302")
	flags.Bool("post303", false, "Do not switch to GET after following a 303")
	flags.String("preproxy", "", "Go via the proxy first")
	flags.BoolP("progress-bar", "#", false, "Display transfer progress as a bar")
	flags.String("proto", "", "Enable/disable PROTOCOLS")
	flags.String("proto-default", "", "Use PROTOCOL for any URL missing a scheme")
	flags.String("proto-redir", "", "Enable/disable PROTOCOLS on redirect")
	flags.StringP("proxy", "x", "", "Use this proxy")
	flags.Bool("proxy-anyauth", false, "Pick any proxy authentication method")
	flags.Bool("proxy-basic", false, "Use Basic authentication on the proxy")
	flags.String("proxy-cacert", "", "CA certificate to verify peer against for proxy")
	flags.String("proxy-capath", "", "CA directory to verify peer against for proxy")
	flags.String("proxy-cert", "", "Set client certificate for proxy")
	flags.String("proxy-cert-type", "", "Client certificate type for proxy")
	flags.String("proxy-ciphers", "", "SSL ciphers to use for proxy")
	flags.String("proxy-crlfile", "", "Set a CRL file for proxy")
	flags.Bool("proxy-digest", false, "Use Digest authentication on the proxy")
	flags.String("proxy-header", "", "Pass custom header to proxy")
	flags.Bool("proxy-http2", false, "Use HTTP/2 for proxy connections")
	flags.Bool("proxy-insecure", false, "Do https proxy connections without verifying the proxy")
	flags.String("proxy-key", "", "Private key for proxy")
	flags.String("proxy-key-type", "", "Private key file type for proxy")
	flags.Bool("proxy-negotiate", false, "Use HTTP Negotiate (SPNEGO) authentication on the proxy")
	flags.Bool("proxy-ntlm", false, "Use NTLM authentication on the proxy")
	flags.String("proxy-pass", "", "Pass phrase for the private key for proxy")
	flags.String("proxy-service-name", "", "SPNEGO proxy service name")
	flags.Bool("proxy-ssl-allow-beast", false, "Allow security flaw for interoperability with older servers")
	flags.String("proxy-tls13-ciphers", "", "TLS 1.3 proxy ciphersuites")
	flags.String("proxy-tlsauthtype", "", "TLS authentication type for proxy")
	flags.String("proxy-tlspassword", "", "TLS password for proxy")
	flags.String("proxy-tlsuser", "", "TLS username for proxy")
	flags.Bool("proxy-tlsv1", false, "Use TLSv1 for proxy")
	flags.StringP("proxy-user", "U", "", "Proxy user and password")
	flags.String("proxy1.0", "", "Use HTTP/1.0 proxy on given port")
	flags.BoolP("proxytunnel", "p", false, "Tunnel through proxy")
	flags.String("pubkey", "", "Public key file name")
	flags.String("random-file", "", "File for reading random data from")
	flags.StringP("range", "r", "", "Retrieve only the bytes within RANGE")
	flags.String("rate", "", "Request rate for serial transfers")
	flags.Bool("raw", false, "Do HTTP 'raw'; no transfer decoding")
	flags.StringP("referer", "e", "", "Send Referer Page information")
	flags.BoolP("remote-header-name", "J", false, "Use the header-provided filename")
	flags.BoolP("remote-name", "O", false, "Write output to a file named as the remote file")
	flags.BoolP("remote-time", "R", false, "Set remote file's time on local output")
	flags.Bool("remove-on-error", false, "Remove output file on errors")
	flags.StringP("request", "X", "", "Specify request method to use")
	flags.String("request-target", "", "Specify the target for this request")
	flags.String("resolve", "", "Resolve the host+port to this address")
	flags.Int("retry", 0, "Retry request if transient problems occur")
	flags.Bool("retry-all-errors", false, "Retry on all errors (use with --retry)")
	flags.Bool("retry-connrefused", false, "Retry on connection refused (use with --retry)")
	flags.Int("retry-delay", 0, "Wait time between retries")
	flags.Int("retry-max-time", 0, "Retry only within this period")
	flags.Bool("sasl-ir", false, "Enable initial response in SASL authentication")
	flags.String("service-name", "", "SPNEGO service name")
	flags.BoolP("show-error", "S", false, "Show error even when -s is used")
	flags.BoolP("show-headers", "i", false, "Include protocol response headers in the output")
	flags.BoolP("silent", "s", false, "Silent mode")
	flags.Bool("skip-existing", false, "Skip download if local file already exists")
	flags.String("socks4", "", "SOCKS4 proxy on given host + port")
	flags.String("socks4a", "", "SOCKS4a proxy on given host + port")
	flags.String("socks5", "", "SOCKS5 proxy on given host + port")
	flags.Bool("socks5-gssapi-nec", false, "Compatibility with NEC SOCKS5 server")
	flags.String("socks5-gssapi-service", "", "SOCKS5 proxy service name for GSS-API")
	flags.String("socks5-hostname", "", "SOCKS5 proxy, pass host name to proxy")
	flags.IntP("speed-limit", "Y", 0, "Stop transfers slower than this")
	flags.IntP("speed-time", "y", 0, "Trigger 'speed-limit' abort after this time")
	flags.Bool("ssl", false, "Try SSL/TLS")
	flags.Bool("ssl-allow-beast", false, "Allow security flaw for interoperability with older servers")
	flags.Bool("ssl-auto-client-cert", false, "Try to find and use auto client certificate")
	flags.Bool("ssl-no-revoke", false, "Disable cert revocation checks (WinSSL)")
	flags.Bool("ssl-reqd", false, "Require SSL/TLS")
	flags.Bool("ssl-revoke-best-effort", false, "Ignore missing/offline cert distribution points")
	flags.BoolP("sslv2", "2", false, "Use SSLv2 (deprecated)")
	flags.BoolP("sslv3", "3", false, "Use SSLv3 (deprecated)")
	flags.String("stderr", "", "Where to redirect stderr")
	flags.Bool("styled-output", false, "Enable styled output for HTTP headers")
	flags.Bool("suppress-connect-headers", false, "Suppress proxy CONNECT response headers")
	flags.Bool("tcp-fastopen", false, "Use TCP Fast Open")
	flags.Bool("tcp-nodelay", false, "Use the TCP_NODELAY option")
	flags.String("telnet-option", "", "Set telnet option")
	flags.Bool("tftp-no-options", false, "Do not send any TFTP options")
	flags.StringP("time-cond", "z", "", "Transfer based on a time condition")
	flags.String("tls-max", "", "Set maximum allowed TLS version")
	flags.String("tls13-ciphers", "", "TLS 1.3 ciphersuites")
	flags.String("tlsauthtype", "", "TLS authentication type")
	flags.String("tlspassword", "", "TLS password")
	flags.String("tlsuser", "", "TLS user name")
	flags.BoolP("tlsv1", "1", false, "Use TLSv1.0 or greater")
	flags.Bool("tlsv1.0", false, "Use TLSv1.0 or greater")
	flags.Bool("tlsv1.1", false, "Use TLSv1.1 or greater")
	flags.Bool("tlsv1.2", false, "Use TLSv1.2 or greater")
	flags.Bool("tlsv1.3", false, "Use TLSv1.3 or greater")
	flags.Bool("tr-encoding", false, "Request compressed transfer encoding")
	flags.String("trace", "", "Write a debug trace to FILE")
	flags.String("trace-ascii", "", "Like --trace, but without hex output")
	flags.String("trace-config", "", "Details to log in trace/verbose")
	flags.Bool("trace-ids", false, "Add transfer IDs to trace/verbose output")
	flags.Bool("trace-time", false, "Add time stamps to trace/verbose output")
	flags.String("unix-socket", "", "Connect through this Unix domain socket")
	flags.StringP("upload-file", "T", "", "Transfer local FILE to destination")
	flags.String("url", "", "URL to work with")
	flags.BoolP("use-ascii", "B", false, "Use ASCII/text transfer")
	flags.StringP("user", "u", "", "Server user and password")
	flags.StringP("user-agent", "A", "", "Send User-Agent <name> to server")
	flags.String("variable", "", "Set variable")
	flags.BoolP("verbose", "v", false, "Make the operation more talkative")
	flags.StringP("write-out", "w", "", "Use output FORMAT after completion")
	flags.Bool("xattr", false, "Store metadata in extended file attributes")
}
