package cobracurl

import (
	"testing"

	"github.com/spf13/pflag"
	"github.com/stretchr/testify/assert"
)

func TestRegisterFlags(t *testing.T) {
	flagSet := pflag.NewFlagSet("test", pflag.ContinueOnError)

	RegisterFlags(flagSet)

	tests := []struct {
		name         string
		flagName     string
		expectedType string
	}{
		{"Append flag", "append", "bool"},
		{"Cookie flag", "cookie", "string"},
		{"Compressed flag", "compressed", "bool"},
		{"Data flag", "data", "string"},
		{"Fail flag", "fail", "bool"},
		{"Form flag", "form", "string"},
		{"Head flag", "head", "string"},
		{"Header flag", "header", "string"},
		{"Get flag", "get", "string"},
		{"Include flag", "include", "bool"},
		{"Insecure flag", "insecure", "bool"},
		{"JSON flag", "json", "string"},
		{"Method flag", "method", "string"},
		{"Output flag", "output", "string"},
		{"Location flag", "location", "bool"},
		{"Proxy flag", "proxy", "string"},
		{"Silent flag", "silent", "bool"},
		{"Referer flag", "referer", "string"},
		{"Remote-name flag", "remote-name", "string"},
		{"Upload-file flag", "upload-file", "string"},
		{"URL flag", "url", "string"},
		{"User-agent flag", "user-agent", "string"},
		{"User flag", "user", "string"},
		{"Verbose flag", "verbose", "bool"},
		{"Cacert flag", "cacert", "string"},
		{"Capath flag", "capath", "string"},
		{"Cert flag", "cert", "string"},
		{"Cert-status flag", "cert-status", "bool"},
		{"Cert-type flag", "cert-type", "string"},
		{"Ciphers flag", "ciphers", "string"},
		{"Connect-timeout flag", "connect-timeout", "int"},
		{"Continue-at flag", "continue-at", "int64"},
		{"Crlf flag", "crlf", "bool"},
		{"Crlfile flag", "crlfile", "string"},
		{"Delegation flag", "delegation", "string"},
		{"Dns-interface flag", "dns-interface", "string"},
		{"Dns-ipv4-addr flag", "dns-ipv4-addr", "string"},
		{"Dns-ipv6-addr flag", "dns-ipv6-addr", "string"},
		{"Dns-servers flag", "dns-servers", "string"},
		{"Doh-url flag", "doh-url", "string"},
		{"Dump-header flag", "dump-header", "string"},
		{"Egd-file flag", "egd-file", "string"},
		{"Engine flag", "engine", "string"},
		{"Etag-compare flag", "etag-compare", "string"},
		{"Etag-save flag", "etag-save", "string"},
		{"Expect100-timeout flag", "expect100-timeout", "int"},
		{"Fail-early flag", "fail-early", "bool"},
		{"False-start flag", "false-start", "bool"},
		{"Form-string flag", "form-string", "string"},
		{"Ftp-account flag", "ftp-account", "string"},
		{"Ftp-alternative-to-user flag", "ftp-alternative-to-user", "string"},
		{"Ftp-create-dirs flag", "ftp-create-dirs", "bool"},
		{"Ftp-method flag", "ftp-method", "string"},
		{"Ftp-pasv flag", "ftp-pasv", "bool"},
		{"Ftp-port flag", "ftp-port", "string"},
		{"Ftp-pret flag", "ftp-pret", "bool"},
		{"Ftp-skip-pasv-ip flag", "ftp-skip-pasv-ip", "bool"},
		{"Ftp-ssl-ccc flag", "ftp-ssl-ccc", "bool"},
		{"Ftp-ssl-ccc-mode flag", "ftp-ssl-ccc-mode", "string"},
		{"Ftp-ssl-control flag", "ftp-ssl-control", "bool"},
		{"Happy-eyeballs-timeout-ms flag", "happy-eyeballs-timeout-ms", "int"},
		{"Haproxy-protocol flag", "haproxy-protocol", "bool"},
		{"Hostpubmd5 flag", "hostpubmd5", "string"},
		{"Http0.9 flag", "http0.9", "bool"},
		{"Http1.0 flag", "http1.0", "bool"},
		{"Http1.1 flag", "http1.1", "bool"},
		{"Http2 flag", "http2", "bool"},
		{"Http2-prior-knowledge flag", "http2-prior-knowledge", "bool"},
		{"Http3 flag", "http3", "bool"},
		{"Ignore-content-length flag", "ignore-content-length", "bool"},
		{"Keepalive-time flag", "keepalive-time", "int"},
		{"Key flag", "key", "string"},
		{"Key-type flag", "key-type", "string"},
		{"Krb flag", "krb", "string"},
		{"Limit-rate flag", "limit-rate", "string"},
		{"Local-port flag", "local-port", "string"},
		{"Login-options flag", "login-options", "string"},
		{"Mail-auth flag", "mail-auth", "string"},
		{"Mail-from flag", "mail-from", "string"},
		{"Mail-rcpt flag", "mail-rcpt", "string"},
		{"Max-filesize flag", "max-filesize", "int64"},
		{"Max-redirs flag", "max-redirs", "int"},
		{"Max-time flag", "max-time", "int"},
		{"Metalink flag", "metalink", "bool"},
		{"Negotiate flag", "negotiate", "bool"},
		{"Netrc flag", "netrc", "bool"},
		{"Netrc-file flag", "netrc-file", "string"},
		{"Netrc-optional flag", "netrc-optional", "bool"},
		{"Next flag", "next", "bool"},
		{"No-alpn flag", "no-alpn", "bool"},
		{"No-buffer flag", "no-buffer", "bool"},
		{"No-keepalive flag", "no-keepalive", "bool"},
		{"No-npn flag", "no-npn", "bool"},
		{"No-sessionid flag", "no-sessionid", "bool"},
		{"Noproxy flag", "noproxy", "string"},
		{"Ntlm flag", "ntlm", "bool"},
		{"Ntlm-wb flag", "ntlm-wb", "bool"},
		{"Oauth2-bearer flag", "oauth2-bearer", "string"},
		{"Pass flag", "pass", "string"},
		{"Path-as-is flag", "path-as-is", "bool"},
		{"Pinnedpubkey flag", "pinnedpubkey", "string"},
		{"Post301 flag", "post301", "bool"},
		{"Post302 flag", "post302", "bool"},
		{"Post303 flag", "post303", "bool"},
		{"Preproxy flag", "preproxy", "bool"},
		{"Proto flag", "proto", "string"},
		{"Proto-default flag", "proto-default", "string"},
		{"Proto-redir flag", "proto-redir", "string"},
		{"Proxy-anyauth flag", "proxy-anyauth", "bool"},
		{"Proxy-basic flag", "proxy-basic", "bool"},
		{"Proxy-cacert flag", "proxy-cacert", "string"},
		{"Proxy-capath flag", "proxy-capath", "string"},
		{"Proxy-cert flag", "proxy-cert", "string"},
		{"Proxy-cert-type flag", "proxy-cert-type", "string"},
		{"Proxy-ciphers flag", "proxy-ciphers", "string"},
		{"Proxy-crlfile flag", "proxy-crlfile", "string"},
		{"Proxy-digest flag", "proxy-digest", "bool"},
		{"Proxy-header flag", "proxy-header", "string"},
		{"Proxy-http2 flag", "proxy-http2", "bool"},
		{"Proxy-insecure flag", "proxy-insecure", "bool"},
		{"Proxy-key flag", "proxy-key", "string"},
		{"Proxy-key-type flag", "proxy-key-type", "string"},
		{"Proxy-negotiate flag", "proxy-negotiate", "bool"},
		{"Proxy-ntlm flag", "proxy-ntlm", "bool"},
		{"Proxy-pass flag", "proxy-pass", "string"},
		{"Proxy-service-name flag", "proxy-service-name", "string"},
		{"Proxy-ssl-allow-beast flag", "proxy-ssl-allow-beast", "bool"},
		{"Proxy-tls13-ciphers flag", "proxy-tls13-ciphers", "string"},
		{"Proxy-tlsauthtype flag", "proxy-tlsauthtype", "string"},
		{"Proxy-tlspassword flag", "proxy-tlspassword", "string"},
		{"Proxy-tlsuser flag", "proxy-tlsuser", "string"},
		{"Proxy-tlsv1 flag", "proxy-tlsv1", "bool"},
		{"Proxy1.0 flag", "proxy1.0", "string"},
		{"Pubkey flag", "pubkey", "string"},
		{"Random-file flag", "random-file", "string"},
		{"Range flag", "range", "string"},
		{"Raw flag", "raw", "bool"},
		{"Request-target flag", "request-target", "string"},
		{"Resolve flag", "resolve", "string"},
		{"Retry flag", "retry", "int"},
		{"Retry-connrefused flag", "retry-connrefused", "bool"},
		{"Retry-delay flag", "retry-delay", "int"},
		{"Retry-max-time flag", "retry-max-time", "int"},
		{"Sasl-ir flag", "sasl-ir", "bool"},
		{"Service-name flag", "service-name", "string"},
		{"Socks4 flag", "socks4", "string"},
		{"Socks4a flag", "socks4a", "string"},
		{"Socks5 flag", "socks5", "string"},
		{"Socks5-gssapi-nec flag", "socks5-gssapi-nec", "bool"},
		{"Socks5-gssapi-service flag", "socks5-gssapi-service", "string"},
		{"Socks5-hostname flag", "socks5-hostname", "string"},
		{"Speed-limit flag", "speed-limit", "int"},
		{"Speed-time flag", "speed-time", "int"},
		{"Ssl flag", "ssl", "bool"},
		{"Ssl-allow-beast flag", "ssl-allow-beast", "bool"},
		{"Ssl-no-revoke flag", "ssl-no-revoke", "bool"},
		{"Ssl-reqd flag", "ssl-reqd", "bool"},
		{"Ssl-revoke-best-effort flag", "ssl-revoke-best-effort", "bool"},
		{"Stderr flag", "stderr", "string"},
		{"Styled-output flag", "styled-output", "bool"},
		{"Suppress-connect-headers flag", "suppress-connect-headers", "bool"},
		{"Tcp-fastopen flag", "tcp-fastopen", "bool"},
		{"Tcp-nodelay flag", "tcp-nodelay", "bool"},
		{"Telnet-option flag", "telnet-option", "string"},
		{"Tftp-no-options flag", "tftp-no-options", "bool"},
		{"Time-cond flag", "time-cond", "string"},
		{"Tls-max flag", "tls-max", "string"},
		{"Tls13-ciphers flag", "tls13-ciphers", "string"},
		{"Tlsauthtype flag", "tlsauthtype", "string"},
		{"Tlspassword flag", "tlspassword", "string"},
		{"Tlsuser flag", "tlsuser", "string"},
		{"Tr-encoding flag", "tr-encoding", "bool"},
		{"Trace flag", "trace", "string"},
		{"Trace-ascii flag", "trace-ascii", "string"},
		{"Trace-time flag", "trace-time", "bool"},
		{"Unix-socket flag", "unix-socket", "string"},
		{"Use-ascii flag", "use-ascii", "bool"},
		{"Write-out flag", "write-out", "string"},
		{"Xattr flag", "xattr", "bool"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			flag := flagSet.Lookup(tt.flagName)
			assert.NotNil(t, flag, "Flag should be registered")
			assert.Equal(t, tt.expectedType, flag.Value.Type(), "Flag type should match")
		})
	}
}
